"""
   usage: python3 match_atom_types.py
      1. [path file to mol2 file generated using antechamber]
      2. [path file to mol2 file generated by R.E.D. Server Development]
      3. [path file to corrected mol2 file]
"""

import sys

# command line inputs
mol2_file = sys.argv[1]
RED_file  = sys.argv[2]
new_file  = sys.argv[3]


atoms_dict = {}
check      = False
with open(RED_file, "r") as RED:
    for line in RED:
        line_split = line.split()
        if (check) and (len(line_split) > 1):
            atoms_dict.update({line_split[1]: line_split[5]})
        elif line_split:
            if (line_split[0] == "@<TRIPOS>ATOM"):
                check = True
            elif (line_split[0] == "@<TRIPOS>BOND"):
                break

# Get lines for new file
lines = []
check = False
done  = False
with open(mol2_file, "r") as file:
    for line in file:
        write_line = line
        line_split = line.split()
        if not done:
            if (check) and (len(line_split) > 1):
                if line_split[1] in atoms_dict:
                    if atoms_dict[line_split[1]] != line_split[5]: # atoms don't match
                        write_line = line.replace(line_split[5], atoms_dict[line_split[1]])
            elif line_split:
                if (line_split[0] == "@<TRIPOS>ATOM"):
                    check = True
                elif (line_split[0] == "@<TRIPOS>BOND"):
                    done  = True
        lines.append(write_line)

 with open(new_file, "w+") as file:
     for line in lines:
         file.write(line)
